services:
  webapi:
    build: .
    image: student-api:latest
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__Default=Host=db;Port=5432;Username=postgres;Password=postgres;Database=student_grades
    networks:
      - student-net

  db:
    image: postgres:14.8
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student_grades
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - student-net

volumes:
  pgdata:

networks:
  student-net:
