version: '3.8'

services:
  postgres:
    image: postgres:14.8-wormbook
    container_name: student-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: student_user
      POSTGRES_PASSWORD: student_pass
      POSTGRES_DB: student_grades
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
