// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using student_grades_api.Data;

#nullable disable

namespace student_grades_api.Data.Migrations
{
    [DbContext(typeof(StudentGradesContext))]
    [Migration("20250709075105_SeedStudentsGrades")]
    partial class SeedStudentsGrades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("student_grades_api.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Score = 90.0,
                            StudentId = 1,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 2,
                            Score = 85.0,
                            StudentId = 1,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 3,
                            Score = 78.0,
                            StudentId = 1,
                            Subject = "History"
                        },
                        new
                        {
                            Id = 4,
                            Score = 88.0,
                            StudentId = 2,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 5,
                            Score = 91.0,
                            StudentId = 2,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 6,
                            Score = 84.0,
                            StudentId = 2,
                            Subject = "Literature"
                        },
                        new
                        {
                            Id = 7,
                            Score = 76.0,
                            StudentId = 3,
                            Subject = "Physics"
                        },
                        new
                        {
                            Id = 8,
                            Score = 82.0,
                            StudentId = 3,
                            Subject = "Chemistry"
                        },
                        new
                        {
                            Id = 9,
                            Score = 89.0,
                            StudentId = 3,
                            Subject = "Math"
                        });
                });

            modelBuilder.Entity("student_grades_api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Phone")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Liad Raz",
                            Phone = "0555912051"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Yoav Elad",
                            Phone = "0555912281"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Biscuit Potato",
                            Phone = "0585917051"
                        });
                });

            modelBuilder.Entity("student_grades_api.Models.Grade", b =>
                {
                    b.HasOne("student_grades_api.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("student_grades_api.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
